spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_data_project
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: CAR-DATA-APPLICATION